server:
  port: 8080
spring:
  application:
    name: front

  profiles:
#    active: prod
    active: dev

  mvc:
    favicon:
      enabled: false

feign:
  httpclient:
    enabled: true

logging:
  level:
    cn.sunguolei.blog.webfront: debug